list_modes:
  list_modes_enabled:
    default: true
    client: true
  list_modes_thumbnails_categories:
    default: ""
    client: true
  list_modes_gallery_categories:
    default: ""
    client: true
  list_modes_min_thumbnail_height:
    default: 100
    client: true
  list_modes_gallery_default_image:
    default: ""
    client: true
